apiVersion: v1
kind: Service
metadata:
  name: oip-minio-prod
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: oip-minio-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oip-minio-prod
spec:
  selector:
    matchLabels:
      app: oip-minio-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: oip-minio-prod
    spec:
      containers:
      - name: oip-minio-prod
        image: socialalphaoip/minio-microservice:prod
        ports:
        - containerPort: 8080
        env:
          - name: MINIO_HTTPS_ENDPOINT
            value: minio-storage.dev.jaagalabs.com
          - name: MINIO_ACCESS_KEY
            value: jaaga
          - name: MINIO_SECRET_KEY
            value: 1JaagaLove
          - name: ENCRYPTION_KEY
            value: KECbbhlLlqZaoJyqBARhbSwxkCHoTmTh
---